pub mod ai;
mod assignment;
mod cleanup;
pub mod completion_summary;
mod config;
pub mod dashboard;
pub mod dashboard_input;
pub mod dry_run;
pub mod events;
pub(crate) mod git_helpers;
#[cfg(test)]
mod integration_tests;
pub mod merge;
pub mod orchestrator;
mod orchestrator_events;
mod orchestrator_merge;
mod orchestrator_tui;
pub mod output;
pub mod panels;
pub mod ring_buffer;
mod run_loop;
pub mod scheduler;
pub mod shared_types;
pub mod shutdown_types;
pub mod state;
pub mod summary;
pub mod task_preview;
pub mod verify;
pub mod worker;
pub mod worker_runner;
pub mod worker_status;
pub mod worktree;

pub use config::ResolvedConfig;
